// planetsData.js
export const planetsData = [
  {
    name: "Mercury",
    radius: 5,
    distance: 40, // => 0.4 AU if 100 = 1 AU
    speed: 4.15,
    texture: "mercury.jpg",
    temperature: "167°C",
    size: "4,879 km",
    selfRotationSpeed: 0.005,
    albedo: 0.06,
    greenhouse: 0,
    dayDuration: "58.6 Earth days",
    yearDuration: "88 Earth days",
    possibilityOfLife: "No",
    distanceFromEarth: "77 million km (closest)",
    // New fields:
    surfaceGravity: "3.7 m/s²",
    axialTilt: "0.034°",
    atmosphericComposition: "Almost none (trace amounts)",
    magneticField: "Weak",
    ringSystem: "No",
    discoveryInfo: "Known since ancient times",
    escapeVelocity: "4.25 km/s",
    keyMissions: "Mariner 10 (1974), MESSENGER (2011)",
    moons: []
  },
  {
    name: "Venus",
    radius: 9,
    distance: 70,
    speed: 1.62,
    texture: "venus.jpg",
    temperature: "464°C",
    size: "12,104 km",
    selfRotationSpeed: 0.002,
    albedo: 0.77,
    greenhouse: 500,
    dayDuration: "243 Earth days",
    yearDuration: "225 Earth days",
    possibilityOfLife: "No",
    distanceFromEarth: "38 million km (closest)",
    surfaceGravity: "8.87 m/s²",
    axialTilt: "177.4°",
    atmosphericComposition: "96.5% CO₂, 3.5% N₂",
    magneticField: "Weak induced",
    ringSystem: "No",
    discoveryInfo: "Known since ancient times",
    escapeVelocity: "10.36 km/s",
    keyMissions: "Venera (USSR), Magellan (NASA)",
    moons: []
  },
  {
    name: "Earth",
    radius: 10,
    distance: 100,
    speed: 1,
    texture: "earth.jpg",
    temperature: "15°C",
    size: "12,742 km",
    selfRotationSpeed: 0.02,
    albedo: 0.3,
    greenhouse: 33,
    dayDuration: "24 hours",
    yearDuration: "365 days",
    possibilityOfLife: "Yes",
    distanceFromEarth: "0 km",
    surfaceGravity: "9.8 m/s²",
    axialTilt: "23.4°",
    atmosphericComposition: "78% N₂, 21% O₂, 1% Ar & others",
    magneticField: "Yes (strong)",
    ringSystem: "No",
    discoveryInfo: "Not applicable",
    escapeVelocity: "11.186 km/s",
    keyMissions: "All human space missions",
    moons: [
      {
        name: "Moon",
        radius: 2.7,
        distance: 15,
        speed: 2.5,
        texture: "moon.jpg",
        temperature: "−20°C",
        size: "3,474 km",
        albedo: 0.12,
        greenhouse: 0,
        dayDuration: "27.3 Earth days",
        yearDuration: "27.3 Earth days",
        possibilityOfLife: "No",
        distanceFromEarth: "384,400 km",
        surfaceGravity: "1.62 m/s²",
        axialTilt: "1.54°",
        atmosphericComposition: "Extremely thin",
        magneticField: "Very weak",
        ringSystem: "No",
        discoveryInfo: "Known since prehistory",
        escapeVelocity: "2.38 km/s",
        keyMissions: "Apollo (1969-1972)"
      }
    ]
  },
  {
    name: "Mars",
    radius: 7,
    distance: 150,
    speed: 0.53,
    texture: "mars.jpg",
    temperature: "−60°C",
    size: "6,779 km",
    selfRotationSpeed: 0.018,
    albedo: 0.15,
    greenhouse: 0,
    dayDuration: "24.6 hours",
    yearDuration: "687 Earth days",
    possibilityOfLife: "Potential (unconfirmed)",
    distanceFromEarth: "54.6 million km (closest)",
    surfaceGravity: "3.71 m/s²",
    axialTilt: "25.2°",
    atmosphericComposition: "95% CO₂, 2.6% N₂, 1.9% Ar",
    magneticField: "No global field, remnant magnetism",
    ringSystem: "No",
    discoveryInfo: "Known since ancient times",
    escapeVelocity: "5.03 km/s",
    keyMissions: "Viking, Spirit, Opportunity, Curiosity, Perseverance",
    moons: [
      {
        name: "Phobos",
        radius: 1.5,
        distance: 9.5,
        speed: 4.0,
        texture: "phobos.jpg",
        temperature: "−40°C",
        size: "22 km",
        albedo: 0.07,
        greenhouse: 0,
        dayDuration: "7.66 hours",
        yearDuration: "7.66 hours",
        possibilityOfLife: "No",
        distanceFromEarth: "Varies with Mars",
        surfaceGravity: "0.0057 m/s²",
        axialTilt: "Locked to Mars",
        atmosphericComposition: "None",
        magneticField: "None",
        ringSystem: "No",
        discoveryInfo: "Asaph Hall, 1877",
        escapeVelocity: "~0.011 km/s",
        keyMissions: "Imaged by multiple Mars orbiters"
      },
      {
        name: "Deimos",
        radius: 1,
        distance: 12,
        speed: 3.5,
        texture: "deimos.jpg",
        temperature: "−40°C",
        size: "12 km",
        albedo: 0.07,
        greenhouse: 0,
        dayDuration: "30.3 hours",
        yearDuration: "30.3 hours",
        possibilityOfLife: "No",
        distanceFromEarth: "Varies with Mars",
        surfaceGravity: "0.003 m/s²",
        axialTilt: "Locked to Mars",
        atmosphericComposition: "None",
        magneticField: "None",
        ringSystem: "No",
        discoveryInfo: "Asaph Hall, 1877",
        escapeVelocity: "~0.0056 km/s",
        keyMissions: "Imaged by Mars orbiters"
      }
    ]
  },
  {
    name: "Jupiter",
    radius: 18,
    distance: 250,
    speed: 0.08,
    texture: "jupiter.jpg",
    temperature: "−108°C",
    size: "139,820 km",
    selfRotationSpeed: 0.04,
    albedo: 0.51,
    greenhouse: 0,
    dayDuration: "9.9 hours",
    yearDuration: "11.86 Earth years",
    possibilityOfLife: "No",
    distanceFromEarth: "~588 million km (closest)",
    surfaceGravity: "24.79 m/s²",
    axialTilt: "3.13°",
    atmosphericComposition: "Mostly H₂ & He",
    magneticField: "Very strong",
    ringSystem: "Yes (faint)",
    discoveryInfo: "Known since ancient times",
    escapeVelocity: "59.5 km/s",
    keyMissions: "Pioneer 10, Voyager, Galileo, Juno",
    moons: [
      {
        name: "Io",
        radius: 3,
        distance: 25,
        speed: 1.8,
        texture: "io.jpg",
        temperature: "110°C",
        size: "3,643 km",
        albedo: 0.63,
        greenhouse: 0,
        dayDuration: "~42 hours",
        yearDuration: "1.77 Earth days",
        possibilityOfLife: "No",
        distanceFromEarth: "Varies with Jupiter",
        surfaceGravity: "1.796 m/s²",
        axialTilt: "~0° (negligible)",
        atmosphericComposition: "SO₂ traces",
        magneticField: "None (within Jupiter's field)",
        ringSystem: "No",
        discoveryInfo: "Galileo Galilei, 1610",
        escapeVelocity: "2.558 km/s",
        keyMissions: "Voyager, Galileo, New Horizons, Juno"
      },
      {
        name: "Europa",
        radius: 2.5,
        distance: 30,
        speed: 1.3,
        texture: "europa.jpg",
        temperature: "−160°C",
        size: "3,121 km",
        albedo: 0.68,
        greenhouse: 0,
        dayDuration: "~85 hours",
        yearDuration: "3.55 Earth days",
        possibilityOfLife: "Potential (subsurface ocean)",
        distanceFromEarth: "Varies with Jupiter",
        surfaceGravity: "1.314 m/s²",
        axialTilt: "~0.1°",
        atmosphericComposition: "Thin O₂",
        magneticField: "No",
        ringSystem: "No",
        discoveryInfo: "Galileo Galilei, 1610",
        escapeVelocity: "2.025 km/s",
        keyMissions: "Voyager, Galileo, Europa Clipper (upcoming)"
      }
    ]
  },
  {
    name: "Saturn",
    radius: 15,
    distance: 400,
    speed: 0.03,
    texture: "saturn.jpg",
    temperature: "−139°C",
    size: "116,460 km",
    selfRotationSpeed: 0.03,
    albedo: 0.47,
    greenhouse: 0,
    dayDuration: "10.7 hours",
    yearDuration: "29.5 Earth years",
    possibilityOfLife: "No",
    distanceFromEarth: "~1.2 billion km (closest)",
    surfaceGravity: "10.44 m/s²",
    axialTilt: "26.7°",
    atmosphericComposition: "Mostly H₂ & He",
    magneticField: "Strong (less than Jupiter)",
    ringSystem: "Yes (prominent)",
    discoveryInfo: "Known since ancient times",
    escapeVelocity: "35.5 km/s",
    keyMissions: "Pioneer 11, Voyager 1 & 2, Cassini-Huygens",
    moons: [
      {
        name: "Titan",
        radius: 4,
        distance: 35,
        speed: 1.1,
        texture: "titan.jpg",
        temperature: "−179°C",
        size: "5,151 km",
        albedo: 0.22,
        greenhouse: 21,
        dayDuration: "~16 Earth days",
        yearDuration: "15.95 Earth days",
        possibilityOfLife: "Potential (complex atmosphere)",
        distanceFromEarth: "Varies with Saturn",
        surfaceGravity: "1.352 m/s²",
        axialTilt: "Locked to Saturn",
        atmosphericComposition: "N₂ ~98.4%, CH₄ ~1.6%",
        magneticField: "None",
        ringSystem: "No",
        discoveryInfo: "Christiaan Huygens, 1655",
        escapeVelocity: "2.64 km/s",
        keyMissions: "Voyager 1, Cassini-Huygens"
      }
    ]
  },
  {
    name: "Uranus",
    radius: 12,
    distance: 600,
    speed: 0.01,
    texture: "uranus.jpg",
    temperature: "−195°C",
    size: "50,724 km",
    selfRotationSpeed: 0.025,
    albedo: 0.51,
    greenhouse: 0,
    dayDuration: "17.2 hours",
    yearDuration: "84 Earth years",
    possibilityOfLife: "No",
    distanceFromEarth: "~2.6 billion km (closest)",
    surfaceGravity: "8.87 m/s²",
    axialTilt: "97.8°",
    atmosphericComposition: "H₂, He, CH₄",
    magneticField: "Yes, off-center",
    ringSystem: "Yes",
    discoveryInfo: "William Herschel, 1781",
    escapeVelocity: "21.3 km/s",
    keyMissions: "Voyager 2 (flyby)",
    moons: [
      {
        name: "Titania",
        radius: 2,
        distance: 20,
        speed: 0.8,
        texture: "titania.jpg",
        temperature: "−200°C",
        size: "1,578 km",
        albedo: 0.27,
        greenhouse: 0,
        dayDuration: "Locked to Uranus",
        yearDuration: "8.71 Earth days",
        possibilityOfLife: "No",
        distanceFromEarth: "Varies with Uranus",
        surfaceGravity: "~0.38 m/s²",
        axialTilt: "Locked to Uranus",
        atmosphericComposition: "Very thin or none",
        magneticField: "None",
        ringSystem: "No",
        discoveryInfo: "William Herschel, 1787",
        escapeVelocity: "~0.76 km/s",
        keyMissions: "Voyager 2 imaging"
      }
    ]
  },
  {
    name: "Neptune",
    radius: 11,
    distance: 800,
    speed: 0.006,
    texture: "neptune.jpg",
    temperature: "−200°C",
    size: "49,244 km",
    selfRotationSpeed: 0.03,
    albedo: 0.41,
    greenhouse: 0,
    dayDuration: "16.1 hours",
    yearDuration: "164.8 Earth years",
    possibilityOfLife: "No",
    distanceFromEarth: "~4.3 billion km (closest)",
    surfaceGravity: "11.15 m/s²",
    axialTilt: "28.3°",
    atmosphericComposition: "H₂, He, CH₄",
    magneticField: "Yes, off-center",
    ringSystem: "Yes (thin)",
    discoveryInfo: "Urbain Le Verrier & Johann Galle, 1846",
    escapeVelocity: "23.5 km/s",
    keyMissions: "Voyager 2 (flyby)",
    moons: [
      {
        name: "Triton",
        radius: 2.5,
        distance: 15,
        speed: 0.7,
        texture: "triton.jpg",
        temperature: "−235°C",
        size: "2,706 km",
        albedo: 0.76,
        greenhouse: 0,
        dayDuration: "Synchronous",
        yearDuration: "5.88 Earth days",
        possibilityOfLife: "No",
        distanceFromEarth: "Varies with Neptune",
        surfaceGravity: "0.779 m/s²",
        axialTilt: "Retrograde orbit",
        atmosphericComposition: "Nitrogen, trace methane",
        magneticField: "None",
        ringSystem: "No",
        discoveryInfo: "William Lassell, 1846",
        escapeVelocity: "1.455 km/s",
        keyMissions: "Voyager 2"
      }
    ]
  },
  {
    name: "Pluto",
    radius: 4,
    distance: 1000,
    speed: 0.002,
    texture: "pluto.jpg",
    temperature: "−225°C",
    size: "2,376 km",
    selfRotationSpeed: 0.01,
    albedo: 0.3,
    greenhouse: 0,
    dayDuration: "6.39 Earth days",
    yearDuration: "248 Earth years",
    possibilityOfLife: "No",
    distanceFromEarth: "~5.0 billion km (closest)",
    surfaceGravity: "0.62 m/s²",
    axialTilt: "119.6°",
    atmosphericComposition: "Thin N₂, CH₄, CO",
    magneticField: "None",
    ringSystem: "No",
    discoveryInfo: "Clyde Tombaugh, 1930",
    escapeVelocity: "1.21 km/s",
    keyMissions: "New Horizons (2015)",
    moons: [
      {
        name: "Charon",
        radius: 1.5,
        distance: 10,
        speed: 0.5,
        texture: "charon.jpg",
        temperature: "−210°C",
        size: "1,212 km",
        albedo: 0.35,
        greenhouse: 0,
        dayDuration: "6.39 Earth days (locked)",
        yearDuration: "6.39 Earth days",
        possibilityOfLife: "No",
        distanceFromEarth: "Varies with Pluto",
        surfaceGravity: "~0.28 m/s²",
        axialTilt: "Locked to Pluto",
        atmosphericComposition: "Very thin or none",
        magneticField: "None",
        ringSystem: "No",
        discoveryInfo: "James W. Christy, 1978",
        escapeVelocity: "~0.58 km/s",
        keyMissions: "New Horizons (2015)"
      }
    ]
  }
];
